spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: postgres
    password: qwerty123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: aidashkooo13@gmail.com
    password: jzex cjcc teax uqzu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret-key: springsecurityuserpasswordadmin123sdfserfdwfwe
  token-lifetime: 10m

logging:
  file:
    name: online_store_app.log
  level:
    root: info
  logback:
    rollingpolicy:
      file-name-pattern: online_store_app-%d{-dd-MM-yyyy}-%i.log.zip
      max-file-size: 5KB